In [1]:
import datetime as dt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

import matplotlib.ticker as tkr
pd.options.mode.chained_assignment = None
pd.set_option('display.max_columns', None)

pd.set_option('display.width', 220)

In [2]:
data_full = pd.read_csv('../data/spotify_dataset.csv')
# data_full.drop(columns=['Unnamed: 0'], inplace=True)
data_full.head()

,Index,Highest Charting Position,Number of Times Charted,Week of Highest Charting,Song Name,Streams,Artist,Artist Followers,Song ID,Genre,Release Date,Weeks Charted,Popularity,Danceability,Energy,Loudness,Speechiness,Acousticness,Liveness,Tempo,Duration (ms),Valence,Chord
0,1,1,8,2021-07-23--2021-07-30,Beggin',"48,633,449",Måneskin,3377762,3Wrjm47oTz2sjIgck11l5e,"['indie rock italiano', 'italian pop']",2017-12-08,2021-07-23--2021-07-30\n2021-07-16--2021-07-23...,100,0.714,0.8,-4.808,0.0504,0.127,0.359,134.002,211560,0.589,B
1,2,2,3,2021-07-23--2021-07-30,STAY (with Justin Bieber),"47,248,719",The Kid LAROI,2230022,5HCyWlXZPP0y6Gqq8TgA20,['australian hip hop'],2021-07-09,2021-07-23--2021-07-30\n2021-07-16--2021-07-23...,99,0.591,0.764,-5.484,0.0483,0.0383,0.103,169.928,141806,0.478,C#/Db
2,3,1,11,2021-06-25--2021-07-02,good 4 u,"40,162,559",Olivia Rodrigo,6266514,4ZtFanR9U6ndgddUvNcjcG,['pop'],2021-05-21,2021-07-23--2021-07-30\n2021-07-16--2021-07-23...,99,0.563,0.664,-5.044,0.154,0.335,0.0849,166.928,178147,0.688,A
3,4,3,5,2021-07-02--2021-07-09,Bad Habits,"37,799,456",Ed Sheeran,83293380,6PQ88X9TkUIAUIZJHW2upE,"['pop', 'uk pop']",2021-06-25,2021-07-23--2021-07-30\n2021-07-16--2021-07-23...,98,0.808,0.897,-3.712,0.0348,0.0469,0.364,126.026,231041,0.591,B
4,5,5,1,2021-07-23--2021-07-30,INDUSTRY BABY (feat. Jack Harlow),"33,948,454",Lil Nas X,5473565,27NovPIUIRrOZoCHxABJwK,"['lgbtq+ hip hop', 'pop rap']",2021-07-23,2021-07-23--2021-07-30,96,0.736,0.704,-7.409,0.0615,0.0203,0.0501,149.995,212000,0.894,D#/Eb

In [3]:
data_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1556 entries, 0 to 1555
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Index                      1556 non-null   int64
 1   Highest Charting Position  1556 non-null   int64
 2   Number of Times Charted    1556 non-null   int64
 3   Week of Highest Charting   1556 non-null   object
 4   Song Name                  1556 non-null   object
 5   Streams                    1556 non-null   object
 6   Artist                     1556 non-null   object
 7   Artist Followers           1556 non-null   object
 8   Song ID                    1556 non-null   object
 9   Genre                      1556 non-null   object
 10  Release Date               1556 non-null   object
 11  Weeks Charted              1556 non-null   object
 12  Popularity                 1556 non-null   object
 13  Danceability               1556 non-null   object
 14  Energy                     1556 non-null   object
 15  Loudness                   1556 non-null   object
 16  Speechiness                1556 non-null   object
 17  Acousticness               1556 non-null   object
 18  Liveness                   1556 non-null   object
 19  Tempo                      1556 non-null   object
 20  Duration (ms)              1556 non-null   object
 21  Valence                    1556 non-null   object
 22  Chord                      1556 non-null   object
dtypes: int64(3), object(20)
memory usage: 279.7+ KB

In [4]:
data_full.isnull().sum()

Index                        0
Highest Charting Position    0
Number of Times Charted      0
Week of Highest Charting     0
Song Name                    0
Streams                      0
Artist                       0
Artist Followers             0
Song ID                      0
Genre                        0
Release Date                 0
Weeks Charted                0
Popularity                   0
Danceability                 0
Energy                       0
Loudness                     0
Speechiness                  0
Acousticness                 0
Liveness                     0
Tempo                        0
Duration (ms)                0
Valence                      0
Chord                        0
dtype: int64

In [5]:
data_full.describe()

             Index  Highest Charting Position  Number of Times Charted
count  1556.000000                1556.000000              1556.000000
mean    778.500000                  87.744216                10.668380
std     449.322824                  58.147225                16.360546
min       1.000000                   1.000000                 1.000000
25%     389.750000                  37.000000                 1.000000
50%     778.500000                  80.000000                 4.000000
75%    1167.250000                 137.000000                12.000000
max    1556.000000                 200.000000               142.000000

In [6]:
data_full.describe(include='object')

,Week of Highest Charting,Song Name,Streams,Artist,Artist Followers,Song ID,Genre,Release Date,Weeks Charted,Popularity,Danceability,Energy,Loudness,Speechiness,Acousticness,Liveness,Tempo,Duration (ms),Valence,Chord
count,1556,1556,1556,1556,1556,1556,1556,1556,1556,1556,1556,1556,1556,1556,1556,1556,1556,1556,1556,1556
unique,83,1556,1556,716,600,1517,395,478,775,70,530,575,1394,772,965,606,1461,1486,732,13
top,2019-12-27--2020-01-03,Beggin',"48,633,449",Taylor Swift,42227614,,[],2020-01-17,2020-12-18--2020-12-25,75,,,,0.102,,0.103,,,,C#/Db
freq,89,1,1,52,52,11,75,34,32,67,11,11,11,15,11,23,11,11,11,214

In [7]:
data_full.drop('Index', axis=1, inplace=True)
data_full.head()

,Highest Charting Position,Number of Times Charted,Week of Highest Charting,Song Name,Streams,Artist,Artist Followers,Song ID,Genre,Release Date,Weeks Charted,Popularity,Danceability,Energy,Loudness,Speechiness,Acousticness,Liveness,Tempo,Duration (ms),Valence,Chord
0,1,8,2021-07-23--2021-07-30,Beggin',"48,633,449",Måneskin,3377762,3Wrjm47oTz2sjIgck11l5e,"['indie rock italiano', 'italian pop']",2017-12-08,2021-07-23--2021-07-30\n2021-07-16--2021-07-23...,100,0.714,0.8,-4.808,0.0504,0.127,0.359,134.002,211560,0.589,B
1,2,3,2021-07-23--2021-07-30,STAY (with Justin Bieber),"47,248,719",The Kid LAROI,2230022,5HCyWlXZPP0y6Gqq8TgA20,['australian hip hop'],2021-07-09,2021-07-23--2021-07-30\n2021-07-16--2021-07-23...,99,0.591,0.764,-5.484,0.0483,0.0383,0.103,169.928,141806,0.478,C#/Db
2,1,11,2021-06-25--2021-07-02,good 4 u,"40,162,559",Olivia Rodrigo,6266514,4ZtFanR9U6ndgddUvNcjcG,['pop'],2021-05-21,2021-07-23--2021-07-30\n2021-07-16--2021-07-23...,99,0.563,0.664,-5.044,0.154,0.335,0.0849,166.928,178147,0.688,A
3,3,5,2021-07-02--2021-07-09,Bad Habits,"37,799,456",Ed Sheeran,83293380,6PQ88X9TkUIAUIZJHW2upE,"['pop', 'uk pop']",2021-06-25,2021-07-23--2021-07-30\n2021-07-16--2021-07-23...,98,0.808,0.897,-3.712,0.0348,0.0469,0.364,126.026,231041,0.591,B
4,5,1,2021-07-23--2021-07-30,INDUSTRY BABY (feat. Jack Harlow),"33,948,454",Lil Nas X,5473565,27NovPIUIRrOZoCHxABJwK,"['lgbtq+ hip hop', 'pop rap']",2021-07-23,2021-07-23--2021-07-30,96,0.736,0.704,-7.409,0.0615,0.0203,0.0501,149.995,212000,0.894,D#/Eb

In [8]:
data_full['Release Date'] = pd.to_datetime(data_full['Release Date'], format='%Y-%m-%d', errors='coerce')

In [9]:
int_columns = ['Streams', 'Artist Followers', 'Popularity', 'Duration (ms)']

data_full['Streams'] = data_full['Streams'].str.replace(',', '')
data_full['Artist Followers'] = data_full['Artist Followers'].str.replace(' ', '0')
data_full['Popularity'] = data_full['Popularity'].str.replace(' ', '0')
data_full['Duration (ms)'] = data_full['Duration (ms)'].str.replace(' ', '0')

for col in int_columns:
    data_full[col] = data_full[col].astype('int64')

In [10]:
numeric_columns = ['Danceability', 'Energy', 'Loudness', 'Speechiness', 'Acousticness', 'Liveness', 'Tempo', 'Valence']
for col in numeric_columns:
    data_full[col] = pd.to_numeric(data_full[col], errors='coerce')

In [11]:
data_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1556 entries, 0 to 1555
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Highest Charting Position  1556 non-null   int64
 1   Number of Times Charted    1556 non-null   int64
 2   Week of Highest Charting   1556 non-null   object
 3   Song Name                  1556 non-null   object
 4   Streams                    1556 non-null   int64
 5   Artist                     1556 non-null   object
 6   Artist Followers           1556 non-null   int64
 7   Song ID                    1556 non-null   object
 8   Genre                      1556 non-null   object
 9   Release Date               1545 non-null   datetime64[ns]
 10  Weeks Charted              1556 non-null   object
 11  Popularity                 1556 non-null   int64
 12  Danceability               1545 non-null   float64
 13  Energy                     1545 non-null   float64
 14  Loudness                   1545 non-null   float64
 15  Speechiness                1545 non-null   float64
 16  Acousticness               1545 non-null   float64
 17  Liveness                   1545 non-null   float64
 18  Tempo                      1545 non-null   float64
 19  Duration (ms)              1556 non-null   int64
 20  Valence                    1545 non-null   float64
 21  Chord                      1556 non-null   object
dtypes: datetime64[ns](1), float64(8), int64(6), object(7)
memory usage: 267.6+ KB

In [12]:
data_full.isnull().sum()

Highest Charting Position     0
Number of Times Charted       0
Week of Highest Charting      0
Song Name                     0
Streams                       0
Artist                        0
Artist Followers              0
Song ID                       0
Genre                         0
Release Date                 11
Weeks Charted                 0
Popularity                    0
Danceability                 11
Energy                       11
Loudness                     11
Speechiness                  11
Acousticness                 11
Liveness                     11
Tempo                        11
Duration (ms)                 0
Valence                      11
Chord                         0
dtype: int64

In [13]:
data_full.describe()

,Highest Charting Position,Number of Times Charted,Streams,Artist Followers,Popularity,Danceability,Energy,Loudness,Speechiness,Acousticness,Liveness,Tempo,Duration (ms),Valence
count,1556.000000,1556.000000,1.556000e+03,1.556000e+03,1556.000000,1545.000000,1545.000000,1545.000000,1545.000000,1545.000000,1545.000000,1545.000000,1556.000000,1545.000000
mean,87.744216,10.668380,6.340219e+06,1.461286e+07,69.593830,0.689997,0.633495,-6.348474,0.123656,0.248695,0.181202,122.811023,196541.492288,0.514704
std,58.147225,16.360546,3.369479e+06,1.666242e+07,16.826585,0.142444,0.161577,2.509281,0.110383,0.250326,0.144071,29.591088,49824.675446,0.227326
min,1.000000,1.000000,4.176083e+06,0.000000e+00,0.000000,0.150000,0.054000,-25.166000,0.023200,0.000025,0.019700,46.718000,0.000000,0.032000
25%,37.000000,1.000000,4.915322e+06,1.990790e+06,65.000000,0.599000,0.532000,-7.491000,0.045600,0.048500,0.096600,97.960000,168728.500000,0.343000
50%,80.000000,4.000000,5.275748e+06,6.852509e+06,73.000000,0.707000,0.642000,-5.990000,0.076500,0.161000,0.124000,122.012000,193303.500000,0.512000
75%,137.000000,12.000000,6.455044e+06,2.253630e+07,80.000000,0.796000,0.752000,-4.711000,0.165000,0.388000,0.217000,143.860000,218766.000000,0.691000
max,200.000000,142.000000,4.863345e+07,8.333778e+07,100.000000,0.980000,0.970000,1.509000,0.884000,0.994000,0.962000,205.272000,588139.000000,0.979000

In [14]:
data_full.describe(include='object')

       Week of Highest Charting Song Name        Artist Song ID Genre           Weeks Charted  Chord
count                      1556      1556          1556    1556  1556                    1556   1556
unique                       83      1556           716    1517   395                     775     13
top      2019-12-27--2020-01-03   Beggin'  Taylor Swift            []  2020-12-18--2020-12-25  C#/Db
freq                         89         1            52      11    75                      32    214

In [15]:
data_full['Lead Artist'] = data_full['Artist'].str.split(',').str[0]

In [16]:
data_full['Date of Highest Charting'] = data_full['Week of Highest Charting'].str.split('--').str[0]
data_full['Date of Highest Charting'] = pd.to_datetime(data_full['Date of Highest Charting'], format='%Y-%m-%d')

In [18]:
data_full.to_csv('../data/spotify_dataset_clean.csv', index=False)